### PR TITLE
Downloader improvements - updated system and bug fixes

### LINKED ISSUE #71: Toggle for generation of JSON file
Its always generating a JSON file for each downloaded video. It would be really great to have a toggle to have the json generation on/off. Thanks

### LINKED ISSUE #76: Default settings (-f bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4) only download 720p or lower anymore.
I think by default youtuble-dl grabs best quality anyhow, so maybe setting this is kinda passé anyhow?

A setting to change this globally (subs and on-demand) would be helpful. I'm open to grabbing VP9 or AV1 as well if the codecs are provided.

I'm a bit busy atm, but there are even more intricate ways to figure out the best quality. It isn't always what youtuble-dl auto-picks, but personally I'm already pretty fine with whatever is the highest res.

Maybe an option to prefer open codecs could be nice for those who fancy the ultimate independence? :)

Ok, maybe a bit of a tangent there. Let's leave it at a bug report for now. :)

Log with two attempts:

```
2020-05-08T06:46:40.211Z INFO: YoutubeDL-Material v4.0 started on PORT 17442
2020-05-08T07:21:49.042Z ERROR: Unexpected end of JSON input
(node:1) UnhandledPromiseRejectionWarning: ReferenceError: req is not defined
at Readable.<anonymous> (/app/app.js:1425:38)
at Readable.emit (events.js:228:7)
at endReadableNT (_stream_readable.js:1185:12)
at processTicksAndRejections (internal/process/task_queues.js:81:21)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:1) UnhandledPromiseRejectionWarning: ReferenceError: req is not defined
at Readable.<anonymous> (/app/app.js:1425:38)
at Readable.emit (events.js:228:7)
at endReadableNT (_stream_readable.js:1185:12)
at processTicksAndRejections (internal/process/task_queues.js:81:21)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:1) UnhandledPromiseRejectionWarning: ReferenceError: req is not defined
at Readable.<anonymous> (/app/app.js:1425:38)
at Readable.emit (events.js:228:7)
at endReadableNT (_stream_readable.js:1185:12)
at processTicksAndRejections (internal/process/task_queues.js:81:21)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

### PR DESCRIPTION
**Pull request by Tzahi12345**
Hi all!

This PR is designed to give users greater flexibility in their downloads and the data associated with it. It also fixes a nasty bug where the max quality was limited to the max mp4 quality available (if another video format existed with a higher quality, it was ignored).

While I intended to switch out the youtube-dl library used (see #111), I came up short of that goal as better alternatives didn't really exist. The one library that was promising didn't have all the features needed, so I decided to instead improve upon the existing functionality.

# Updates

### There is now only 1 downloading method

Previously, there was a "safe" and "normal" downloading method. The safe method was exactly that: safe. All args worked as expected, any errors seen were problems with youtube-dl and not with the driver or this app. But, it lacked one important feature: the progress bar. The normal method, on the other hand, didn't work with all args (e.g. `--write-thumbnail`), but it had a progress bar and was generally quick.

All of that is scrapped, the "safe" method is now the only one used, and the downloading progress is now estimated on our end! Best of both worlds :)

This refactor fixes #76 as well, allowing any quality video to be downloaded (up to 4K).

### Thumbnails are autodownloaded

The title to this is a bit misleading -- it's not just that thumbnails get autodownloaded, but downloaded thumbnails are *automatically* used as the thumbnail in the UI. If you don't want a thumbnail downloaded, that's alright! Just disable it in the settings and the thumbnail URL.

### JSON metadata is now optional

Because of the improvements in PR #136, it is now possible to delete the JSON metadata after download. We'll still keep the metadata in the DB, and your folders will be nice and clean. This fixes #71!

----------------------

That's pretty much it folks! If you have anything to add, now is the time to do it as I'll probably finish up and merge this in the next few days or so :)

### CODE REVIEW

File: backend/app.js [hunk 1]
```diff
@@ -1559,47 +1605,26 @@ function updateDownloads() {
...
+    const filename = path.format(path.parse(download['_filename'].substring(0, download['_filename'].length-4)));
+    const resulting_file_size = download['filesize'];
+
+    glob(`${filename}*`, (err, files) => {
+        let sum_size = 0;
+        files.forEach(file => {
+            try {
+                const file_stats = fs.statSync(file);
+                if (file_stats && file_stats.size) {
+                    sum_size += file_stats.size;
```
Comment (Tzahi12345) [inline backend/app.js:1619]: This is more of an art than a science, we're just selecting files that start with the file name (thus capturing the parts being downloaded in files named like so: `<video title>.<format>.<ext>.part`). Any file that starts with `<video title>` will be counted as part of the "bytes downloaded", which will be divided by the "total expected bytes."

Because of the uncertainty involved, sometimes percent complete can reach as high as 200%. Weird, until you consider that the parts must be combined into one video, and only then can the parts be deleted. Right before the deletion happens, 2 copies of the video exists. One in parts, one stitched together. And at that point, progress is calculated to be at >100%.

File: backend/app.js [hunk 2]
```diff
@@ -1821,7 +1846,7 @@ app.post('/api/tomp3', optionalJwt, async function(req, res) {
     const is_playlist = url.includes('playlist');
 
     let result_obj = null;
-    if (safeDownloadOverride || is_playlist || options.customQualityConfiguration || options.customArgs || options.maxBitrate)
+    if (true || safeDownloadOverride || is_playlist || options.customQualityConfiguration || options.customArgs || options.maxBitrate)
```
Comment (Tzahi12345) [inline backend/app.js:1849]: Override that will force the "safe" mode

File: backend/app.js [hunk 3]
```diff
@@ -1833,6 +1858,7 @@ app.post('/api/tomp3', optionalJwt, async function(req, res) {
 });
 
 app.post('/api/tomp4', optionalJwt, async function(req, res) {
+    req.setTimeout(0); // remove timeout in case of long videos
```
Comment (Tzahi12345) [inline backend/app.js:1861]: For large video files, the request timeout was often reached. Here, we remove it to prevent duplicate download requests.
